/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_test_jnidemo_JniText */

#ifndef _Included_com_android_test_jnidemo_JniText
#define _Included_com_android_test_jnidemo_JniText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_test_jnidemo_JniText
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_test_jnidemo_JniText_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
